name: CI/CD Pipeline

on: push

jobs:
  check-xml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install XML linting tool
      run: sudo apt-get update && sudo apt-get install -y libxml2-utils
    - name: List all XML files
      run: |
        find . -type f -name "*.xml"
    - name: Check XML syntax
      run: |
        set -e
        for file in $(find . -type f -name "*.xml"); do
          xmllint --noout $file
        done
    - name: Complete
      run: echo "All XML files have been checked."

  test-apex:
    runs-on: ubuntu-latest
    needs: check-xml
    steps:
    - uses: actions/checkout@v3
    - name: Install Salesforce CLI
      run: npm install sfdx-cli --global

    - name: Authenticate with Salesforce
      run: sfdx auth:jwt:grant --client-id ${{ secrets.SF_CLIENT_ID }} --jwt-key-file ${{ secrets.SF_JWT_KEY }} --username ${{ secrets.SF_USERNAME }} --instance-url https://login.salesforce.com
    
    - name: Push source to scratch org
      run: sfdx force:source:push
    
    - name: Run Apex tests
      run: sfdx force:apex:test:run --resultformat junit --outputdir test-results --codecoverage --testlevel RunLocalTests
    
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results

  deploy-production:
    runs-on: ubuntu-latest
    needs: test-apex
    if: success()
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Salesforce CLI
      run: npm install sfdx-cli --global
    
    - name: Authenticate with Salesforce
      run: sfdx auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} --jwtkeyfile ${{ secrets.SF_JWT_KEY }} --username ${{ secrets.SF_PROD_USERNAME }} --instanceurl https://login.salesforce.com
    
    - name: Deploy to production
      run: sfdx force:source:deploy -p packaged
    
    - name: Run post-deployment tests
      run: sfdx force:apex:test:run --resultformat junit --outputdir test-results-production --codecoverage --testlevel RunLocalTests
    
    - name: Archive production test results
      uses: actions/upload-artifact@v3
      with:
        name: production-test-results
        path: test-results-production